### ISSUE TITLE
Send Stefanie your short bio blurb

### ISSUE THREAD

**Issue by stefrie** [Loki-Code201/foodwise#28]

**Comment by KasonBraley** [comment]
Kason is a Navy veteran with a passion for software development and solving everyday problems. His hobbies include spending time with his fiance and two dogs, playing Chess, and playing Ice Hockey

**Comment by KasonBraley** [comment]
https://github.com/Loki-Code201/foodwise/commit/8e79bd4f0135f88791e67bf7d4d57f09bd4d3be1
